# Generated by Django 5.0.3 on 2024-03-19 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_project_blog_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project_blog',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='project_blog',
            name='description',
            field=models.TextField(),
        ),
    ]
